local K, C, _ = select(2, ...):unpack()

-- If you're saving frame positions, use "UIParent", not UIParent
C["position"] = {
	["achievements"] = {"TOP", "UIParent", "TOP", 0, -22},
	["bag"] = {"RIGHT", "UIParent", "RIGHT", -140, -20},
	["bank"] = {"LEFT", "UIParent", "LEFT", 23, 150},
	["bg_score"] = {"BOTTOMLEFT", "ActionButton12", "BOTTOMRIGHT", 10, 0},
	["player_buffs"] = {"TOPRIGHT", "UIParent", "TOPRIGHT", -21, -21},
	["bn_popup"] = {"BOTTOMLEFT", "ChatFrame1", "TOPLEFT", 4, 54},
	["capturebar"] = {"TOP", "UIParent", "TOP", 0, -170},
	["chat"] = {"BOTTOMLEFT", "UIParent", "BOTTOMLEFT", 3, 5},
	["group_loot"] = {"BOTTOM", "UIParent", "BOTTOM", -238, 700},
	["locframe"] = {"TOP", "Minimap", "BOTTOM", 0, -12},
	["loot"] = {"TOPLEFT", "UIParent", "TOPLEFT", 245, -220},
	["minimap"] = {"TOPRIGHT", "UIParent", "TOPRIGHT", -7, -7},
	["minimap_buttons"] = {"TOPRIGHT", "Minimap", "TOPLEFT", -3, 2},
	["pet_horizontal"] = {"BOTTOMRIGHT", "UIParent", "BOTTOM", -175, 167},
	["powerbar"] = {"BOTTOM", "ActionBarAnchor", "TOP", 0, 130},
	["quest"] = {"TOPRIGHT", "UIParent", "TOPRIGHT", -K.ScreenHeight / 5, -K.ScreenHeight / 4},
	["stance_bar"] = {"BOTTOMRIGHT", "UIParent", "BOTTOM", -202, 167},
	["bottom_bars"] = {"BOTTOM", "UIParent", "BOTTOM", 0, 5},
	["statsframe"] = {"TOP", "Minimap", "BOTTOM", 0, -12},
	["exprepframe"] = {"TOP", "Minimap", "BOTTOM", 0, 0},
	["ticket"] = {"TOPLEFT", "UIParent", "TOPLEFT", 0, -1},
	["tooltip"] = {"BOTTOMRIGHT", "UIParent", "BOTTOMRIGHT", -3, 3},
	["uierror"] = {"TOP", "UIParent", "TOP", 0, -30},
	["vehicle"] = {"TOP", "Minimap", "BOTTOM", 0, -30},
	["right_bars"] = {"BOTTOMRIGHT", "UIParent", "BOTTOMRIGHT", -5, 330},
	["worldmap"] = {"CENTER", "UIParent", "CENTER", 0, 70},
	["vehicle_bar"] = {"BOTTOMRIGHT", "ActionButton1", "BOTTOMLEFT", -3, 0},
	["pulse_cooldown"] = {"CENTER", "UIParent", "CENTER", 0, 0},
	-- UnitFrame positions
	unitframes = {
		["player"] = {"BOTTOMRIGHT", "ActionBarAnchor", "TOPLEFT", -9, 175},
		["target"] = {"BOTTOMLEFT", "ActionBarAnchor", "TOPRIGHT", 9, 175},
		["focus"] = {"BOTTOM", "PlayerFrame", "TOP", 0, 60},
		["arena"] = {"BOTTOMRIGHT", "UIParent", "RIGHT", -60, -70},
		["boss"] = {"BOTTOMRIGHT", "UIParent", "RIGHT", -23, -70},
		["player_castbar"] = {"BOTTOM", "ActionBarAnchor", "TOP", 0, 175},
		["target_castbar"] = {"BOTTOM", "CastingBarFrame", "TOP", 0, 21},
	},
	-- Filger positions
	filger = {
		["cooldown"] = {"BOTTOMRIGHT", "PlayerFrame", "TOPRIGHT", 63, 17},
		["player_buff_icon"] = {"BOTTOMRIGHT", "PlayerFrame", "TOPRIGHT", 2, 173},
		["player_proc_icon"] = {"BOTTOMLEFT", "TargetFrame", "TOPLEFT", -2, 173},
		["pve_cc"] = {"TOPLEFT", "PlayerFrame", "BOTTOMLEFT", -2, -44},
		["pve_debuff"] = {"BOTTOMRIGHT", "PlayerFrame", "TOPRIGHT", 2, 253},
		["special_proc_icon"] = {"BOTTOMRIGHT", "PlayerFrame", "TOPRIGHT", 2, 213},
		["target_bar"] = {"BOTTOMLEFT", "TargetFrame", "BOTTOMRIGHT", 9, -41},
		["target_buff_icon"] = {"BOTTOMLEFT", "TargetFrame", "TOPLEFT", -2, 253},
		["target_debuff_icon"] = {"BOTTOMLEFT", "TargetFrame", "TOPLEFT", -2, 213},
	},
}